export const APP_LOAD = 'APP_LOAD';

export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const REGISTER = 'REGISTER';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';

export const FIELD_VALIDATE_FAIL = 'FIELD_VALIDATE_FAIL';

export const PRODUCT_PAGE_LOADED = 'PRODUCT_PAGE_LOADED';
export const PRODUCT_PAGE_UNLOADED = 'PRODUCT_PAGE_UNLOADED';

export const ERROR_NOTIFIED = 'ERROR_NOTIFIED';

export const NODE_LIST_UNLOAD = 'NODE_LIST_UNLOAD';
export const NODE_LIST_LOAD = 'NODE_LIST_LOAD';



// User
export const USER_LIST_LOAD = 'USER_LIST_LOAD';
export const USER_LIST_UNLOAD = 'USER_LIST_UNLOAD';

export const USER_DELETE = 'USER_DELETE';
export const USER_LIST_REFRESH = 'USER_LIST_REFRESH';

export const USER_EDIT_PAGE_LOAD = 'USER_EDIT_PAGE_LOAD';









