export const APP_LOAD = 'APP_LOAD';

export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const REGISTER = 'REGISTER';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';

export const FIELD_VALIDATE_FAIL = 'FIELD_VALIDATE_FAIL';



// home
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';


// common
export const REDIRECT = 'REDIRECT';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';



// Node
export const NODE_LIST_UNLOAD = 'NODE_LIST_UNLOAD';
export const NODE_LIST_LOAD = 'NODE_LIST_LOAD';
export const NODE_LIST_REFRESH = 'NODE_LIST_REFRESH';
export const NODE_DELETE = 'NODE_DELETE';
export const NODE_ADD = 'NODE_ADD';
export const NODE_ADD_CANCEL = 'NODE_ADD_CANCEL';
export const NODE_MODIFY_PAGE_LOAD = 'NODE_MODIFY_PAGE_LOAD';
export const NODE_MODIFY = 'NODE_MODIFY';
export const NODE_MODIFY_CANCEL = 'NODE_MODIFY_CANCEL';



// User
export const USER_LIST_LOAD = 'USER_LIST_LOAD';
export const USER_LIST_UNLOAD = 'USER_LIST_UNLOAD';
export const USER_DELETE = 'USER_DELETE';
export const USER_LIST_REFRESH = 'USER_LIST_REFRESH';
export const USER_ADD = 'USER_ADD';
export const USER_ADD_CANCLE = 'USER_ADD_CANCLE';
export const USER_MODIFY = 'USER_MODIFY';
export const USER_MODIFY_CANCEL = 'USER_MODIFY_CANCEL';
export const USER_EDIT_PAGE_LOAD = 'USER_EDIT_PAGE_LOAD';

// Notifier
export const NOTIFIER_NOTIFICATION = 'NOTIFIER_NOTIFICATION';
export const NOTIFIER_NOTIFIED = 'NOTIFIER_NOTIFIED';

// Node User
export const NODE_USER_LIST_LOAD = 'NODE_USER_LIST_LOAD';
export const NODE_USER_LIST_UNLOAD = 'NODE_USER_LIST_UNLOAD';
export const NODE_USER_LIST_REFRESH = 'NODE_USER_LIST_REFRESH';









